version: '3.3'

volumes:
  rc-authentication-db:
  rc-backend-db:

networks:
  default:
    external:
      name: research-coder

services:

  # RABBITMQ
  rc-rabbitmq:
    image: rabbitmq:3-management
    container_name: rc-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672

  # API GATEWAY
  rc-api-gateway:
    image: gcr.io/meta-research-data-portal/github-uab-energetics-rc-api-gateway:master
    build:
      context: ./rc-api-gateway
      dockerfile: Dockerfile.dev
    container_name: rc-api-gateway
    env_file: .environments/.env.gateway
    environment:
      RC_BACKEND_HOST: rc-backend:8000
      RC_AUTHENTICATION_HOST: rc-authentication
      PORT: 80
    volumes:
      - ./rc-api-gateway/src:/app/src
    ports:
      - 8080:80

  # AUTHENTICATION SERVICE
  rc-authentication:
    image: gcr.io/meta-research-data-portal/github-uab-energetics-rc-authentication:master
    build:
      context: ./rc-authentication
      dockerfile: Dockerfile.dev
    container_name: rc-authentication
    volumes:
      - .keys/rc-auth.key:/private-key.pem
      - .keys/rc-auth.key.pub:/public-key.pub
      - ./rc-authentication/src:/app/src
      - ./rc-authentication/test:/app/test
    env_file: .env
    environment:
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      MONGO_HOST: rc-authentication-db
      JWT_PRIVATE_KEY: /private-key.pem
      JWT_PUBLIC_KEY: /public-key.pub
    ports:
      - 7000:80


  # AUTHENTICATION SERVICE DATABASE
  rc-authentication-db:
    image: mongo:latest
    container_name: rc-authentication-db
    volumes:
      - rc-authentication-db:/data/db
    ports:
      - 27017:27017

  # MONOLITH API
  rc-backend:
#    image: gcr.io/meta-research-data-portal/github-uab-energetics-research-coder-api:master
    build: 
        context: ./rc-backend
        dockerfile: Dockerfile.dev
    container_name: rc-backend
    volumes:
      - .keys/rc-auth.key.pub:/rc-auth.key.pub
      - ./rc-backend/app:/app/app
      - ./rc-backend/tests:/app/tests
      - ./rc-backend/config:/app/config
      - ./rc-backend/database:/app/database
      - ./rc-backend/resources:/app/resources
      - ./rc-backend/routes:/app/routes
    env_file: .environments/.env.api
    environment:
      DB_HOST: rc-backend-db
      DB_PORT: 3306
      JWT_PUBLIC_KEY: /rc-auth.key.pub
      AUTH_API_SECRET: secret
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - 8000:8000

  rc-backend-queue-worker:
#      image: gcr.io/meta-research-data-portal/github-uab-energetics-research-coder-api:master
      container_name: rc-backend-queue-worker
      restart: unless-stopped
      build:
        context: ./rc-backend
        dockerfile: Dockerfile.dev
      volumes:
        - .keys:/.keys
        - ./rc-backend/app:/app/app
        - ./rc-backend/tests:/app/tests
        - ./rc-backend/config:/app/config
        - ./rc-backend/database:/app/database
        - ./rc-backend/resources:/app/resources
        - ./rc-backend/routes:/app/routes
      environment:
        DB_HOST: rc-backend-db
        DB_PORT: 3306
        JWT_PUBLIC_KEY: /.keys/rc-auth.key.pub
        AUTH_API_SECRET: secret
        RABBITMQ_HOST: rc-rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: guest
        RABBITMQ_PASSWORD: guest
      env_file: .environments/.env.api
      command: php artisan rabbitmq:listen

  # MONOLITH API DATABASE
  rc-backend-db:
    image: mysql:5.7
    container_name: rc-backend-db
    volumes:
      - rc-backend-db:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=research-coder
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  # FRONT END ANGULAR APP
  rc-client:
    image: gcr.io/meta-research-data-portal/github-uab-energetics-rc-client:master
    build:
      context: ./rc-client
      dockerfile: Dockerfile.dev
    container_name: rc-client
    volumes:
      - ./rc-client/src:/app/src
      - ./rc-client/e2e:/app/e2e
    ports:
      - 4200:4200


  # AUTHORIZATION SERVICE
  rc-authorization:
    build: ./rc-authorization
    container_name: rc-authorization
    environment:
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      MYSQL_HOST: rc-authorization-db
      MYSQL_DATABASE: authorization
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - ./rc-authorization/src:/app/src
      - ./rc-authorization/test:/app/test
    ports:
      - 8002:5000

  # DATABASE FOR AUTHORIZATION SERVICE
  rc-authorization-db:
    image: mysql:5.7
    container_name: rc-authorization-db
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: authorization