version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  # RABBITMQ
  rc-rabbitmq:
    image: rabbitmq:3-management
    container_name: rc-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672

  # API GATEWAY
  rc-api-gateway:
    build:
      context: ./rc-api-gateway
      dockerfile: Dockerfile.dev
    container_name: rc-api-gateway
    env_file: .environments/.env.gateway
    environment:
      RC_API_HOST: rc-backend
      RC_AUTHENTICATION_HOST: rc-authentication
      PORT: 80
    ports:
      - 8080:80

  # AUTHENTICATION SERVICE
  rc-authentication:
    build:
      context: ./rc-authentication
      dockerfile: Dockerfile.dev
    container_name: rc-authentication
    volumes:
      - .keys/rc-auth.key:/private-key.pem
      - .keys/rc-auth.key.pub:/public-key.pub
    env_file: .env
    environment:
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      MONGO_HOST: rc-authentication-mongodb
      JWT_PRIVATE_KEY: /private-key.pem
      JWT_PUBLIC_KEY: /public-key.pub
    ports:
      - 7000:80


  # AUTHENTICATION SERVICE DATABASE
  rc-authentication-mongodb:
    image: mongo:latest
    container_name: rc-authentication-mongodb
    ports:
      - 27017:27017

  # MONOLITH API
  rc-backend:
    build: 
        context: ./research-coder-api
        dockerfile: Dockerfile.dev
    container_name: rc-backend
    volumes:
      - .keys/rc-auth.key.pub:/rc-auth.key.pub
      - ./research-coder-api/app:/app/app
      - ./research-coder-api/tests:/app/tests
      - ./research-coder-api/config:/app/config
      - ./research-coder-api/database:/app/database
      - ./research-coder-api/resources:/app/resources
      - ./research-coder-api/routes:/app/routes
    env_file: .environments/.env.api
    environment:
      DB_HOST: rc-backend-db
      DB_PORT: 3306
      JWT_PUBLIC_KEY: /rc-auth.key.pub
      AUTH_API_SECRET: secret
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - 8000:8000

  # MONOLITH API DATABASE
  rc-backend-db:
    image: mysql:5.7
    container_name: rc-backend-db
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=research-coder
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  # FRONT END ANGULAR APP
  rc-client:
    build:
      context: ./rc-client
      dockerfile: Dockerfile.dev
    container_name: rc-client
    volumes:
      - ./rc-client/src:/app/src
      - ./rc-client/e2e:/app/e2e
    ports:
      - 4200:4200

  # HTTP Dispatcher for Backend
  rc-amqp-http-dispatcher:
    build:
      context: ./rc-amqp-http-dispatcher
      dockerfile: Dockerfile.dev
    container_name: rc-amqp-http-dispatcher
    environment:
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      BACKEND_HOST: rc-backend:8000
      BACKEND_SECRET: secret
    ports:
      - 8005:80

  # AUTHORIZATION SERVICE
  rc-authorization:
    build: ./rc-authorization
    container_name: rc-authorization
    environment:
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      MYSQL_HOST: rc-authorization-db
      MYSQL_DATABASE: authorization
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - 8002:5000

  # DATABASE FOR AUTHORIZATION SERVICE
  rc-authorization-db:
    image: mysql:5.7
    container_name: rc-authorization-db
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: authorization