version: '3.3'

volumes:
  db-data-dev:

networks:
  default:
    external:
      name: research-coder

services:

  # API GATEWAY
  rc-api-gateway:
    build:
      context: ./rc-api-gateway
      dockerfile: Dockerfile.dev
    container_name: rc-api-gateway
    env_file: .env.gateway
    environment:
      RC_API_HOST: rc-api
      PORT: 80
    ports:
      - 8001:80

  # AUTH SERVICE
  rc-auth:
    build:
      context: ./rc-auth
      dockerfile: Dockerfile.dev
    container_name: rc-auth
    env_file: .env.auth
    environment:
      RC_API_HOST: rc-api
      PORT: 80
    ports:
      - 8004:80

  # AUTH SERVICE DATABASE
  rc-auth-mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  # MONOLITH API
  rc-api:
    build: ./research-coder-api
    container_name: rc-api
    env_file: .env.api
    environment:
      - DB_HOST=rc-api-db
      - DB_PORT=3306
    ports:
      - 8000:80

  # MONOLITH API DATABASE
  rc-api-db:
    image: mysql:5.7
    container_name: rc-api-db
    ports:
      - 3306:3306
    volumes:
      - db-data-dev:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=research-coder
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  # FRONT END ANGULAR APP
  rc-client:
    build: ./research-coder
    container_name: rc-client
    ports:
      - 4200:4200
