version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  # API GATEWAY
  rc-api-gateway:
    build:
      context: ./rc-api-gateway
      dockerfile: Dockerfile.dev
    container_name: rc-api-gateway
    env_file: .environments/.env.gateway
    environment:
      RC_API_HOST: rc-api
      PORT: 80
    ports:
      - 8080:80

  # AUTH SERVICE
  rc-auth:
    build:
      context: ./rc-auth
      dockerfile: Dockerfile.dev
    container_name: rc-auth
    restart: always
    volumes:
      - .keys/rc-auth-jwt.key:/.keys/rc-auth-jwt.key      # JWT Private Key
      - .keys/rc-auth-jwt.key.pub:/.keys/rc-auth-jwt.key.pub      # JWT Private Key
    env_file: .environments/.env.auth
    environment:
      PORT: 80
    ports:
      - 8004:80

  # AUTH SERVICE DATABASE
  rc-auth-mongodb:
    image: mongo:latest
    container_name: rc-auth-mongodb
    restart: always
    ports:
      - 27017:27017

  # MONOLITH API
  rc-api:
    build: ./research-coder-api
    container_name: rc-api
    volumes:
      - .keys/rc-auth-jwt.key.pub:/.keys/rc-auth-jwt.key.pub    # JWT Public Key
    env_file: .environments/.env.api
    environment:
      - DB_HOST=rc-api-db
      - DB_PORT=3306
    ports:
      - 8000:80

  # MONOLITH API DATABASE
  rc-api-db:
    image: mysql:5.7
    container_name: rc-api-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=research-coder
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  # FRONT END ANGULAR APP
  rc-client:
    build: ./research-coder
    container_name: rc-client
    ports:
      - 4200:4200
