version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  rc-auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rc-auth
    volumes:
      - ./:/app
      - .keys:/.keys
#      - .keys/rc-auth-jwt.key:/.keys/rc-auth-jwt.key      # JWT Private Key
#      - .keys/rc-auth-jwt.key.pub:/.keys/rc-auth-jwt.key.pub      # JWT Private Key
    env_file: .env
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: rc-auth-mongodb
      JWT_PRIVATE_KEY: /.keys/rc-auth.pem
      JWT_PUBLIC_KEY: /.keys/pub/rc-auth.pub
    ports:
      - 7000:80

  rc-auth-mongodb:
    image: mongo:latest
    container_name: rc-auth-mongodb
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
