version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  rc-auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - .keys:/.keys
    env_file:
      - .env
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: database
      SPA_OAUTH_CALLBACK: http://localhost
      JWT_PRIVATE_KEY: /.keys/rc-authentication.pem
      JWT_PUBLIC_KEY: /.keys/pub/rc-authentication.pub
      # GITHUB_CLIENT_ID: secret # REQUIRED FOR GITHUB LOGIN
    ports:
      - 7000:80

  database:
    image: mongo:latest
    ports:
      - 27017:27017

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
